export { type RootProps as DialogProps } from './DialogRoot'
export { type ContentProps as DialogContentProps } from './DialogContent'
export { type HeaderProps as DialogHeaderProps } from './DialogHeader'
export { type BodyProps as DialogBodyProps } from './DialogBody'
export { type FooterProps as DialogFooterProps } from './DialogFooter'
export { type TriggerProps as DialogTriggerProps } from './DialogTrigger'
export { type OverlayProps as DialogOverlayProps } from './DialogOverlay'
export { type PortalProps as DialogPortalProps } from './DialogPortal'
export { type TitleProps as DialogTitleProps } from './DialogTitle'
export { type DescriptionProps as DialogDescriptionProps } from './DialogDescription'
export { type CloseProps as DialogCloseProps } from './DialogClose'
export { type CloseButtonProps as DialogCloseButtonProps } from './DialogCloseButton'

export { Dialog } from './Dialog'
