export { type CloseButtonProps } from './DialogCloseButton'
export { type ContentProps } from './DialogContent'
export { type DescriptionProps } from './DialogDescription'
export { type OverlayProps } from './DialogOverlay'
export { type PortalProps } from './DialogPortal'
export { type TitleProps } from './DialogTitle'
export { type TriggerProps } from './DialogTrigger'
export { type HeaderProps } from './DialogHeader'
export { type BodyProps } from './DialogBody'
export { type FooterProps } from './DialogFooter'

export { Dialog } from './Dialog'
