name: manual-deploy
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Node setup
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - name: Adoption script
        uses: adevinta/spark-action-scan-adoption@v0
        with:
          token: ${{ secrets.SPARK_TOKEN }}
